# Generated by Django 2.1.1 on 2018-09-22 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.CharField(max_length=250)),
                ('art_image', models.CharField(max_length=1000)),
                ('file_type', models.CharField(max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_username', models.CharField(max_length=20)),
                ('artist_name', models.CharField(max_length=100)),
                ('artist_email', models.EmailField(max_length=254)),
                ('artist_profile_pic', models.CharField(max_length=1000)),
                ('artist_genres', models.CharField(max_length=500)),
                ('artist_description', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='art',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist_profile.ArtistProfile'),
        ),
    ]
