# Generated by Django 2.1.1 on 2018-09-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='artistprofile',
            old_name='artist_name',
            new_name='artist_first_name',
        ),
        migrations.AddField(
            model_name='art',
            name='medium',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='artist_last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
