# Generated by Django 2.1.1 on 2018-09-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_profile', '0002_auto_20180922_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='art_completion_date',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art',
            name='art_description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
